version: '3.4'

services:
  registroclientes.api:
    image: ${DOCKER_REGISTRY-}registroclientesapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    hostname: "sqlserver"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Z0AmMM#8j2!o"
    ports:
      - "11433:1433"    
    expose:
      - 1433